stages:
  - test

variables:
  PROJECT_NAME: 'beach-configuration'
  FLOW_PACKAGE_KEY: 'Flownative.Beach.Configuration'
  COMPOSER_PACKAGE_NAME: 'flownative/beach-configuration'
test:
  stage: test
  image: registry.gitlab.com/flownative/docker/composer:7.2
  artifacts:
    paths:
      - '*'
    name: ${PROJECT_NAME}-${CI_COMMIT_SHA}
    when: on_success
    expire_in: 1 day
  script:
    - ls -la
    - mkdir -p DistributionPackages/${FLOW_PACKAGE_KEY}
    - shopt -s extglob
    - "mv !(DistributionPackages) DistributionPackages/${FLOW_PACKAGE_KEY}"
    - 'echo \'{"name": "flownative/flow-test-distribution", "config": {"vendor-dir": "Packages/Libraries", "bin-dir": "bin"}, "repositories": [ {"type": "path",      "url": "DistributionPackages/*"}], "require": {"${COMPOSER_PACKAGE_NAME}": "*"}, "minimum-stability": "dev", "prefer-stable": true, "scripts": {"post-update-cmd": "Neos\\Flow\\Composer\\InstallerScripts::postUpdateAndInstall", "post-install-cmd": "Neos\\Flow\\Composer\\InstallerScripts::postUpdateAndInstall", "post-package-update": "Neos\\Flow\\Composer\\InstallerScripts::postPackageUpdateAndInstall", "post-package-install": "Neos\\Flow\\Composer\\InstallerScripts::postPackageUpdateAndInstall"}}\' > composer.json'
    - composer.json < envsubst > composer.json
    - cat composer.json
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "${CI_REPOSITORY_ACCESS_PRIVATE_KEY}")
    - mkdir -p ~/.ssh && ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - ls -la
    - composer -o -v --no-progress update
    - ls -la
    - Packages/Libraries/phpunit/phpunit/phpunit -c /Build/BuildEssentials/PhpUnit/UnitTests.xml --testdox DistributionPackages/${FLOW_PACKAGE_KEY}/Tests/Unit
